name: Deploy Portfolio to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload to S3
        run: |
          aws s3 cp index.html s3://prachi-portfolio-bucket/index.html \
            --cache-control "max-age=300" \
            --content-type "text/html"

          aws s3 cp main.js s3://prachi-portfolio-bucket/main.js \
            --cache-control "max-age=300" \
            --content-type "application/javascript"

          aws s3 cp theme-init.js s3://prachi-portfolio-bucket/theme-init.js \
            --cache-control "max-age=300" \
            --content-type "application/javascript"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3V2QBK3UCBDEC \
            --paths "/*"

      - name: Deployment complete
        run: echo "Portfolio deployed to https://prachi.workplace-profile.in"